**Question 1**

Theophylline is a drug used for the treatment of diseases such as chronic obstructive pulmonary disease
and asthma. This medicine was administered to 20 subjects over a number of days. Each time the drug
was administered to the subjects, the following measurements were recorded:

| field | description |
|-------|-------------|
|id | a number (1, . . . , 20) identifying the subject on whom the observation was made |
|weight|weight of the subject (kg)|
|dose|dose of theophylline administered orally to the subject (mg/kg)|
|time|time since drug administration when the sample was drawn (hr)|
|conc|theophylline concentration in the sample (mg/L)|

There are 1,000 records in total. You have been provided with an XML file containing this data.

a) Create a function to import this XML file. Your function should include appropriate exception handling
clauses and should return the XML data.

In [28]:
import xml.etree.ElementTree as ET

def importXML(xmlfile):
    try:
        # Parse the XML file directly
        tree = ET.parse(xmlfile)
        root = tree.getroot()  # Get the root element of the XML
        return root
    except FileNotFoundError:
        print(f"Could not open the file: {xmlfile}")
    except ET.ParseError as e:
        print(f"Error parsing XML file {xmlfile}: {e}")
    except (IOError, OSError) as e:
        print(f"An I/O error occurred with file {xmlfile}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
      

theo_xml = importXML("theoDataset.xml")


b) Use the print function to display the ‘id’, ‘weight’ and ‘conc’ of the second, fourth, sixth, eight and tenth records in the XML dataset. (Hint: you may use the range() function). 

In [30]:
for i in range(1,10,2):
    id = theo_xml[i].find('id').text
    weight = theo_xml[i].find('weight').text
    conc = theo_xml[i].find('conc').text
    print('id:{}\tweight:{}\tconc:{}'.format(id,weight,conc))

id:13	weight:73.8	conc:0.66
id:5	weight:88.3	conc:9.47
id:8	weight:81.3	conc:6.43
id:10	weight:75.1	conc:11.25
id:20	weight:67.9	conc:7.84


c) Extract all the XML data and write it to a CSV file. Your file should also contain the column names.

In [41]:
import csv

def xml_to_csv(xml_file, csv_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    with open(csv_file, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        
        # Write header row if needed
        writer.writerow(['id', 'weight','dose','time','conc'])

        for item in root.findall('item'):  # Adjust based on XML structure
            # Extract data from XML
            data1 = item.find('id').text
            data2 = item.find('weight').text
            data3 = item.find('dose').text
            data4 = item.find('time').text
            data5 = item.find('conc').text

            # Write data to CSV
            writer.writerow([data1, data2, data3, data4, data5])

# Example usage
xml_to_csv('theoDataset.xml', 'output.csv')


**Question 2**

a) Create a NumPy array filled with 3000 numbers starting with 1,000. Ensure that your array has 300 rows and 10
columns. 

In [46]:
import numpy as np
a = np.arange(1000,4000).reshape(300,10)
print(a)

[[1000 1001 1002 ... 1007 1008 1009]
 [1010 1011 1012 ... 1017 1018 1019]
 [1020 1021 1022 ... 1027 1028 1029]
 ...
 [3970 3971 3972 ... 3977 3978 3979]
 [3980 3981 3982 ... 3987 3988 3989]
 [3990 3991 3992 ... 3997 3998 3999]]


b) Using **slicing**, split this array into 5 separate arrays. The number of rows in each array should be
equal, and there should still be 5 columns.


In [65]:
a1=a[0:60,:]
a2=a[60:120,:]
a3=a[120:180,:]
a4=a[180:240,:]
a5=a[240:300,:]
print (a1, a2, a3, a4, a5)

[[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009]
 [1010 1011 1012 1013 1014 1015 1016 1017 1018 1019]
 [1020 1021 1022 1023 1024 1025 1026 1027 1028 1029]
 [1030 1031 1032 1033 1034 1035 1036 1037 1038 1039]
 [1040 1041 1042 1043 1044 1045 1046 1047 1048 1049]
 [1050 1051 1052 1053 1054 1055 1056 1057 1058 1059]
 [1060 1061 1062 1063 1064 1065 1066 1067 1068 1069]
 [1070 1071 1072 1073 1074 1075 1076 1077 1078 1079]
 [1080 1081 1082 1083 1084 1085 1086 1087 1088 1089]
 [1090 1091 1092 1093 1094 1095 1096 1097 1098 1099]
 [1100 1101 1102 1103 1104 1105 1106 1107 1108 1109]
 [1110 1111 1112 1113 1114 1115 1116 1117 1118 1119]
 [1120 1121 1122 1123 1124 1125 1126 1127 1128 1129]
 [1130 1131 1132 1133 1134 1135 1136 1137 1138 1139]
 [1140 1141 1142 1143 1144 1145 1146 1147 1148 1149]
 [1150 1151 1152 1153 1154 1155 1156 1157 1158 1159]
 [1160 1161 1162 1163 1164 1165 1166 1167 1168 1169]
 [1170 1171 1172 1173 1174 1175 1176 1177 1178 1179]
 [1180 1181 1182 1183 1184 1185 1186 1187 1188

c) Reshape these 3 of these arrays into any dimensions of your choice. They should all have different
dimensions.

In [72]:
r1 = a1.reshape(75,8)
r2=a2.ravel()
r3=a3.reshape(10,20,3)
print(r1,r2,r3)

[[1000 1001 1002 1003 1004 1005 1006 1007]
 [1008 1009 1010 1011 1012 1013 1014 1015]
 [1016 1017 1018 1019 1020 1021 1022 1023]
 [1024 1025 1026 1027 1028 1029 1030 1031]
 [1032 1033 1034 1035 1036 1037 1038 1039]
 [1040 1041 1042 1043 1044 1045 1046 1047]
 [1048 1049 1050 1051 1052 1053 1054 1055]
 [1056 1057 1058 1059 1060 1061 1062 1063]
 [1064 1065 1066 1067 1068 1069 1070 1071]
 [1072 1073 1074 1075 1076 1077 1078 1079]
 [1080 1081 1082 1083 1084 1085 1086 1087]
 [1088 1089 1090 1091 1092 1093 1094 1095]
 [1096 1097 1098 1099 1100 1101 1102 1103]
 [1104 1105 1106 1107 1108 1109 1110 1111]
 [1112 1113 1114 1115 1116 1117 1118 1119]
 [1120 1121 1122 1123 1124 1125 1126 1127]
 [1128 1129 1130 1131 1132 1133 1134 1135]
 [1136 1137 1138 1139 1140 1141 1142 1143]
 [1144 1145 1146 1147 1148 1149 1150 1151]
 [1152 1153 1154 1155 1156 1157 1158 1159]
 [1160 1161 1162 1163 1164 1165 1166 1167]
 [1168 1169 1170 1171 1172 1173 1174 1175]
 [1176 1177 1178 1179 1180 1181 1182 1183]
 [1184 1185

d) Split 2 of these reshaped arrays column-wise.

In [79]:
s1=np.hsplit(r1, 2)
s2=np.hsplit(r3, 5)
print(s1,s2)

[array([[1000, 1001, 1002, 1003],
       [1008, 1009, 1010, 1011],
       [1016, 1017, 1018, 1019],
       [1024, 1025, 1026, 1027],
       [1032, 1033, 1034, 1035],
       [1040, 1041, 1042, 1043],
       [1048, 1049, 1050, 1051],
       [1056, 1057, 1058, 1059],
       [1064, 1065, 1066, 1067],
       [1072, 1073, 1074, 1075],
       [1080, 1081, 1082, 1083],
       [1088, 1089, 1090, 1091],
       [1096, 1097, 1098, 1099],
       [1104, 1105, 1106, 1107],
       [1112, 1113, 1114, 1115],
       [1120, 1121, 1122, 1123],
       [1128, 1129, 1130, 1131],
       [1136, 1137, 1138, 1139],
       [1144, 1145, 1146, 1147],
       [1152, 1153, 1154, 1155],
       [1160, 1161, 1162, 1163],
       [1168, 1169, 1170, 1171],
       [1176, 1177, 1178, 1179],
       [1184, 1185, 1186, 1187],
       [1192, 1193, 1194, 1195],
       [1200, 1201, 1202, 1203],
       [1208, 1209, 1210, 1211],
       [1216, 1217, 1218, 1219],
       [1224, 1225, 1226, 1227],
       [1232, 1233, 1234, 1235],
       [1

e) Create a new array whose shape is **broadcast compatible** with your original ndarray. It should contain values starting at 500. Multiply this new array by your original array.

In [86]:
b= np.arange(500,510).reshape(1,10)
print(b)

[[500 501 502 503 504 505 506 507 508 509]]


In [88]:
c=a*b
print(c)

[[ 500000  501501  503004 ...  510549  512064  513581]
 [ 505000  506511  508024 ...  515619  517144  518671]
 [ 510000  511521  513044 ...  520689  522224  523761]
 ...
 [1985000 1989471 1993944 ... 2016339 2020824 2025311]
 [1990000 1994481 1998964 ... 2021409 2025904 2030401]
 [1995000 1999491 2003984 ... 2026479 2030984 2035491]]


**Question 3**

a) Given the following string:

`
All I want is a proper cup of coffee
Made in a proper copper coffee pot
I may be off my dot
But I want a cup of coffee
From a proper coffee pot
Tin coffee pots and iron coffee pots
They’re no use to me
If I can’t have a proper cup of coffee
In a proper copper coffee pot
I’ll have a cup of tea`

Write a single function that uses regular expressions to highlight the words “tea”,“dot” or “pot” if they appear at the end of a line.

Your answer should look like this:

`
All I want is a proper cup of coffee
Made in a proper copper coffee {pot}
I may be off my {dot}
But I want a cup of coffee
From a proper coffee {pot}
Tin coffee pots and iron coffee pots
They’re no use to me
If I can’t have a proper cup of coffee
In a proper copper coffee {pot}
I’ll have a cup of {tea}`

In [109]:
import re
s="All I want is a proper cup of coffee Made in a proper copper coffee pot I may be off my dot But I want a cup of coffee From a proper coffee pot Tin coffee pots and iron coffee pots They’re no use to me If I can’t have a proper cup of coffee In a proper copper coffee pot I’ll have a cup of tea"
print(re.compile(r'tea|dot|pot$',re.M).sub('{\g<0>}',s.rstrip()))

All I want is a proper cup of coffee Made in a proper copper coffee pot I may be off my {dot} But I want a cup of coffee From a proper coffee pot Tin coffee pots and iron coffee pots They’re no use to me If I can’t have a proper cup of coffee In a proper copper coffee pot I’ll have a cup of {tea}


<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\valen\AppData\Local\Temp\ipykernel_17068\1085576572.py:3: SyntaxWarning: invalid escape sequence '\g'
  print(re.compile(r'tea|dot|pot$',re.M).sub('{\g<0>}',s.rstrip()))


b) Using regular expressions, write code to highlight all words that begin with the characters `po` or `co`.

Your answer should look like this:

`All I want is a proper cup of {coffee}
Made in a proper {copper} {coffee} {pot}
I may be off my dot
But I want a cup of {coffee}
From a proper {coffee} {pot}
Tin {coffee} {pots} and iron {coffee} {pots}
They’re no use to me
If I can’t have a proper cup of {coffee}
In a proper {copper} {coffee} {pot}
I’ll have a cup of tea`

In [120]:
print(re.compile(r'\bpo|\bco',re.M).sub('{\g<0>}',s.rstrip()))

All I want is a proper cup of {co}ffee Made in a proper {co}pper {co}ffee {po}t I may be off my dot But I want a cup of {co}ffee From a proper {co}ffee {po}t Tin {co}ffee {po}ts and iron {co}ffee {po}ts They’re no use to me If I can’t have a proper cup of {co}ffee In a proper {co}pper {co}ffee {po}t I’ll have a cup of tea


<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\valen\AppData\Local\Temp\ipykernel_17068\3628990417.py:1: SyntaxWarning: invalid escape sequence '\g'
  print(re.compile(r'\bpo|\bco',re.M).sub('{\g<0>}',s.rstrip()))
